<?xml version="1.0" encoding="utf-8" ?>
<!--学生成绩信息-->
<!--这里是约束部分，即内部DTD-->
<!DOCTYPE scores[
  <!ELEMENT scores (student+)>
  <!ELEMENT student (name,course,score)>
  <!ATTLIST student id CDATA #REQUIRED>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT course (#PCDATA)>
  <!--表示只能写可被解析的字符串，不可以在里面嵌套子子元素-->
  <!ELEMENT score (#PCDATA)>
]>
<!--这里开始XML的数据部分-->
<scores>
  <student id="1">
    <name>张三</name>
    <course>Java</course>
    <score>90</score>
  </student>
  <student id="2">
    <name>李四</name>
    <course>C#</course>
    <score>100</score>
  </student>
  <student id="3">
    <name>王五</name>
    <course>汇编</course>
    <score>98</score>
  </student>
</scores>